backend:
  name: github
  repo: farhan-ezaz/findmyscholarship #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true
  # name: test-repo

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://findmyscholarship.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts/
    create: true
    format: frontmatter
    preview_path: post/{{slug}}/
    sortable_fields: ['date', 'title']
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: date }
      - { label: "Featured Image", name: "image", widget: "image" }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Author", name: "authors", wiget: "string", default: "Farhan Ezaz" }
      - {label: Tags, name: tags, widget: select, multiple: true, options: ["usa","europe","australia","canada","middle-east","south-arica","asia","undergraduate-scholarships","masters-scholarships","phd-scholarships","postdoctoral-fellowships","high-school-scholarships","stem","humanities-and-social-sciences","business-and-economics","arts-and-design","medical-and-health-sciences","law-scholarships","fellowships","internships","grants","volunteer-opportunities","professional-development","resources-and-guides"]}
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
