backend:
  name: github
  repo: farhan-ezaz/findmyscholarship #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true
  # name: test-repo

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://findmyscholarship.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts/
    create: true
    format: frontmatter
    preview_path: post/{{slug}}/
    sortable_fields: ['date', 'title']
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: date }
      - { label: "Featured Image", name: "image", widget: "image" }
      - {label: "Authors", name: "authors", widget: select, multiple: true, allow_add: false, options: ["Farhan Ezaz"]}
      # - { label: "Author", name: "authors", wiget: "string", default: "Farhan Ezaz" }
      # - { name: tags2, label: Tags, widget: list, allow_add: true, multiple: true, field: { name: tag1, label: Tag, widget: string } }
      # - { name: tags, label: Tags, widget: list, allow_add: true, field: { name: tag, label: Tag, widget: select, options: ['Tag1', 'Tag2', 'Tag3'] } }
      - {label: Tags, name: tags, widget: select, multiple: true, options: ["usa","europe","australia","canada","middle-east","south-arica","asia","undergraduate-scholarships","masters-scholarships","phd-scholarships","postdoctoral-fellowships","high-school-scholarships","fellowships","internships","grants","volunteer-opportunities","professional-development","resources-and-guides"]}
      # - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { name: body, label: Body, widget: markdown }
  - name: author
    label: Authors
    folder: src/content/authors/
    create: false
    format: frontmatter
    fields: 
      - {name: title, label: "Full Name"}
      - {name: image, label: "Profile Photo", widget: image}
      - {name: description, label: "Description"}
      - name: "social" 
        label: "Social"
        widget: "object"
        summery: "Your social links."
        fields: 
          - {name: facebook, label: "Facebook Link"}
          - {name: twitter, label: "Twitter Link"}
          - {name: instagram, label: "Instagram Link"}
      - {name: body, label: Bio, widget: markdown}